version: "3.8"
services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - '5434:5432'